- hosts: all
  name: Configure server
  user: vagrant
  become: yes
  become_method: sudo
  gather_facts: yes
  vars:
    ssh_users:
      - system_user: "centos"
        github_users:
          - winescout
          - smcfarlane
          - orangewolf
          - dewey4iv
          - adamthayer

    project_name: "{{ project_name }}"
    project_version: "{{ project_version }}"
    project_owner: "{{ project_owner }}"
    git_repo_url: "https://github.com/{{ project_owner }}/{{ project_name }}.git"
    git_repo_branch: "{{ project_version }}"
    cap_deployment: "{{ cap_deployment }}"
    solr_fqdn: "{{ solr_fqdn }}"
    fedora_admin_user: "{{ fc_admin_user }}"
    fedora_admin_password: "{{ fc_admin_password }}"
    fedora_server_fqdn: "{{ solr_fqdn }}"
    rails_host_fqdn: "{{ rails_host_fqdn }}"
    enable_ssl: "no"
    env_name: "production"
  roles:
    - { role: uclalib_role_mysql, mysql_install_version: '5.6' }
    - { role: uclalib_role_apache }
    - { role: uclalib_role_passenger, passenger_version: '5.3.3' }
    - { role: uclalib_role_samvera_capdeploy }
  tasks:
    - name: set up N8 ssh keys
      authorized_key: >
        user="deploy"
        key="https://github.com/{{ item.1 }}.keys"
      with_subelements:
        - "{{ ssh_users }}"
        - github_users
